# Generated by Django 6.0.1 on 2026-04-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity_In_Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Transaction',
            fields=[
                ('Transaction_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Transaction_Type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Transaction_Date', models.DateField(auto_now_add=True)),
                ('Total_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.supplier'),
        ),
    ]
